import './globals.css'
import { Inter, Quicksand } from 'next/font/google'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
import Image from 'next/image'
import VideoBackground from '@/components/videoBackground/VideoBackground'

const inter = Inter({ subsets: ['latin'] })
const quicksand = Quicksand({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <div className="container">
          <VideoBackground />
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
